"""add gender in user

Revision ID: 0f9717f1a2a9
Revises: b1034576aeb7
Create Date: 2026-06-17 16:47:21.532100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9717f1a2a9'
down_revision: Union[str, Sequence[str], None] = 'b1034576aeb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Gender', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Gender')
    # ### end Alembic commands ###
